[package]
name = "whey"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
bio = "3"
owo-colors = "4"
directories = "5"
serde = { version = "1", features = ["derive"] }
toml = "0.8"